Python/PiPython/PiApi/PiUi/Models/ModuleViewModel.cs
using System.Collections.Generic;
using Coordinator.Modules;

namespace PiUi.Models
{
	public class ModuleViewModel
	{
		public List<ExtendedModule> ExtendedModules { get; set; }
	}
}

Python/PiPython/PiApi/PiUi/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataPersistance.Modules;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PiUi.Controllers
{
	[Route("api/log")]
	public class LogController : Controller
	{
		private LogRepository repo;

		public LogController(LogRepository repo)
		{
			this.repo = repo;
		}

		// GET api/<controller>/5
		[HttpGet("{moduleId}/{featureId}")]
		public object Get(int moduleId, int featureId, DateTime from, DateTime to)
		{
			var logs = repo.GetLogs(moduleId, featureId, from, to);
			return logs.Select(x => new {time = x.Time, value = x.Value}).ToArray();
		}
	}
}

Python/PiPython/PiApi/PiUi/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinator.Modules;
using DataPersistance.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PiUi.Models;

namespace PiUi.Controllers
{
    public class ModuleController : Controller
    {
	    private Coordinator.Modules.ModuleController mc;

	    public ModuleController()
	    {
		    mc = new Coordinator.Modules.ModuleController();
	    }

	    // GET: Module
        public ActionResult Index()
        {
	        var vm = new ModuleViewModel
	        {
		        ExtendedModules = mc.Modules
	        };
            return View(vm);
        }

        // GET: Module/Details/5
        public ActionResult Details(int id)
        {
	        var module = mc.GetModule(id);
	        var vm = new DetailModuleViewModel
			{
				Module = module,
				Values = module.GetAllValues()
			};
            return View(vm);
        }

	    public ActionResult Log(int moduleId, int featureId, DateTime from = default(DateTime), DateTime to = default(DateTime), int granularity = 100)
	    {
		    var module = mc.GetModule(moduleId);
		    if (from == default(DateTime))
		    {
			    from = DateTime.UtcNow.AddDays(-1);
			}
		    if (to == default(DateTime))
		    {
			    to = DateTime.UtcNow;
		    }
			var vm = new LogViewModel()
		    {
			    Module = module,
				Feature = module.Features.Single(x => x.Id == featureId),
				Values = module.GetLogValuesForRange(featureId, from, to, granularity)
		    };
		    return View(vm);
	    }

		// GET: Module/Create
		public ActionResult Create()
        {
			var vm = new EditModuleViewModel()
			{
				CurrentFeatures = new List<Feature>(),
				PossibleFeatures = mc.GetAllPossibleFeatures()
			};
            return View("Edit", vm);
        }

        // GET: Module/Edit/5
        public ActionResult Edit(int id)
        {
	        var vm = GetModuleViewModel(id);
	        return View(vm);
        }

	    private EditModuleViewModel GetModuleViewModel(int id)
	    {
		    var module = mc.GetModule(id);
		    var vm = new EditModuleViewModel()
		    {
			    Ip = module.Module.Ip.ToString(),
			    ModuleId = module.Module.Id,
			    CurrentFeatures = module.Features,
			    ModuleName = module.Module.Name,
			    PossibleFeatures = mc.GetAllPossibleFeatures().Where(x => module.Features.All(y => y.Id != x.Id)).ToList()
		    };
		    return vm;
	    }

	    [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditModuleViewModel model)
        {
            try
            {
	            if (model.ModuleId == 0)
	            {
		            mc.AddModule(model.ModuleName, model.Ip);
	            }
	            else
	            {
		            throw new NotImplementedException();
	            }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Edit", model);
            }
		}
		
	    [HttpGet]
	    public ActionResult Delete(int moduleId)
	    {
			throw new NotImplementedException();
		    return RedirectToAction(nameof(Index));
		}
		
	    [HttpPost]
	    [ValidateAntiForgeryToken]
	    public ActionResult AddFeature(EditModuleViewModel model)
	    {
		    mc.GetModule(model.ModuleId).AddFeature(model.FeatureToAdd, model.Interval);

		    return View("Edit", GetModuleViewModel(model.ModuleId));
		}

	    [HttpPost]
	    [ValidateAntiForgeryToken]
	    public ActionResult DeleteFeature(EditModuleViewModel model)
	    {
		    throw new NotImplementedException();
			
		    var featureToDelete = model.CurrentFeatures.Single(x => x.Id == model.FeatureToDelete);
		    model.CurrentFeatures.Remove(featureToDelete);
		    model.PossibleFeatures.Add(featureToDelete);
			return View("Edit", model);
		}

	    [HttpPost]
	    [ValidateAntiForgeryToken]
	    public ActionResult AddStrip(EditModuleViewModel model)
	    {
		    try
		    {
			    var module = mc.GetModule(model.ModuleId);
				module.AddLedValues(model.StartIndex, model.StartX, model.StartY, model.EndIndex, model.EndX, model.EndY);

			    return RedirectToAction(nameof(Index));
		    }
		    catch
		    {
			    return View("Edit", model);
		    }
	    }
	}
}

Python/PiPython/PiApi/PiUi/Views/Module/Details.cshtml
@model DetailModuleViewModel

@{
    ViewBag.Title = "Module Details";
    Layout = "_Layout";
}

<h2>Module Details</h2>

<table>
    <tr>
        <td>
            @Html.Label("Feature")
        </td>
        <td>
            @Html.Label("Value")
        </td>
    </tr>
    @foreach (var value in Model.Values)
    {
        <tr>
            <td>
                @Html.ActionLink(value.Feature.Name, "Log", new
                {
                    moduleId = Model.Module.Module.Id,
                    featureId = value.Feature.Id
                })
            </td>
            <td>
                <label>@value.Lastvalue</label>
            </td>
        </tr>
    }
</table>

Python/PiPython/PiApi/PiUi/Views/Module/Edit.cshtml
@model EditModuleViewModel

@{
    ViewBag.Title = "Update Module";
    Layout = "_Layout";
}

<h2>Update Module</h2>
@Html.ActionLink("Delete", "Delete", Model.ModuleId)
<h3>Data</h3>
@using (Html.BeginForm("Edit", "Module", FormMethod.Post))
{
    <table>
        <tr>
            <td>Name</td>
            <td>@Html.TextBoxFor(x => x.ModuleName)</td>
        </tr>
        <tr>
            <td>Ip</td>
            <td>@Html.TextBoxFor(x => x.Ip)</td>
        </tr>
        <tr>
            <td>
                <button type="submit">Save</button>
            </td>
        </tr>
    </table>
}
<h3>Current Features</h3>
<table>
    <tr>
        <td>Name</td>
        <td></td>
    </tr>
    @foreach (var feature in Model.CurrentFeatures)
    {
        <tr>
            @using (Html.BeginForm("DeleteFeature", "Module", FormMethod.Post))
            {
            <td>
                <input type="hidden" name="ModuleId" value="@Model.ModuleId" />
                <input type="hidden" name="FeatureToRemove" value="@feature.Id" />
                <label>@feature.Name</label>
            </td>
                <td>
                    <button type="submit">Remove</button>
                </td>

            }
        </tr>
    }
</table>
<h3>Possible Features</h3>
<table>
    <tr>
        <td>Name</td>
        <td>Interval</td>
        <td></td>
    </tr>
    @foreach (var feature in Model.PossibleFeatures)
    {
        <tr>
            @using (Html.BeginForm("AddFeature", "Module", FormMethod.Post))
            {
            <td>
                <input type="hidden" name="ModuleId" value="@Model.ModuleId" />
                <input type="hidden" name="FeatureToAdd" value="@feature.Id" />
                <label>@feature.Name</label>
            </td>
                <td>
                    @Html.TextBoxFor(x => x.Interval)
                </td>
                <td>
                    <button type="submit">Add</button>
                </td>

            }
        </tr>
    }
</table>
<h3>Leds</h3>
@using (Html.BeginForm("AddStrip", "Module", FormMethod.Post))
{
<table>
    <tr>
        <input type="hidden" name="ModuleId" value="@Model.ModuleId" />
        <td>Start index</td>
        <td>@Html.TextBoxFor(x => x.StartIndex)</td>
    </tr>
    <tr>
        <td>Start Position</td>
        <td>@Html.TextBoxFor(x => x.StartX)|@Html.TextBoxFor(x => x.StartY)</td>
    </tr>
    <tr>
        <td>End index</td>
        <td>@Html.TextBoxFor(x => x.EndIndex)</td>
    </tr>
    <tr>
        <td>End Position</td>
        <td>@Html.TextBoxFor(x => x.EndX)|@Html.TextBoxFor(x => x.EndY)</td>
    </tr>
    <tr>
        <td>
            <button type="submit">Add</button>
        </td>
    </tr>
</table>
}

Python/PiPython/PiApi/PiUi/Views/Module/Index.cshtml
@model ModuleViewModel

@{
    ViewBag.Title = "Module Overview";
    Layout = "_Layout";
}

<h2>Module Overview</h2>
@Html.ActionLink("Add", "Create")
<table>
    <tr>
    <td>
        @Html.Label("Name")
    </td>
    <td>
        @Html.Label("Direct Link")
    </td>
    <td>
        @Html.Label("Detail")
    </td>
    <td>
        @Html.Label("Edit")
    </td>
    @foreach (var module in Model.ExtendedModules)
    {
        <tr>
            <td>
                @Html.Label(module.Module.Name)
            </td>
            <td>
                @if (!module.IsLocal)
                {
                    <a href=@($"http://{module.Module.Ip}:5000")>Connect</a>
                }
            </td>
            <td>
                @Html.ActionLink("Detail", "Details", new {module.Module.Id})
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {module.Module.Id})
            </td>
        </tr>
    }
</table>